## Student Name: Gabriel Espinoza Rojas

## Student ID: 22176691

# Task 1

## Task 1.a

Use the following code snippet to download [unigrams](https://www.norvig.com/ngrams/count_1w.txt) and [bigrams](https://www.norvig.com/ngrams/count_2w.txt) data, and load them into their corresponding dataframes, unigrams_df and bigrams_df

In [2]:
#from IPython.core.display import display, HTML
from IPython.display import display, HTML
import pandas as pd


!wget https://norvig.com/ngrams/count_1w.txt #unigram data
!wget https://norvig.com/ngrams/count_2w.txt #bigram data

# remove the . before sending it to Colab/submitting
filePath1 = "./content/count_1w.txt"
filePath2 = "./content/count_2w.txt"


unigrams_df = pd.read_csv(filePath1,sep='\t',header=None, names=['unigram','count'])
bigrams_df = pd.read_csv(filePath2,sep='\t',header=None, names=['bigram','count'])


print(unigrams_df.shape, bigrams_df.shape)
print(f'Number of unigrams: {unigrams_df.shape[0]} Number of Bigrams: {bigrams_df.shape[0]}')  # df.size VS df.shape


display(unigrams_df.head(100),bigrams_df.head(100))

--2026-10-01 01:41:25--  https://norvig.com/ngrams/count_1w.txt
Resolviendo norvig.com (norvig.com)... 158.106.138.13
Conectando con norvig.com (norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
Ubicación: https://www.norvig.com/ngrams/count_1w.txt [siguiente]
--2026-10-01 01:41:26--  https://www.norvig.com/ngrams/count_1w.txt
Resolviendo www.norvig.com (www.norvig.com)... 158.106.138.13
Conectando con www.norvig.com (www.norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 4956241 (4,7M) [text/plain]
Guardando como: ‘count_1w.txt.1’

count_1w.txt.1      100%[===================>]   4,73M  3,49MB/s    en 1,4s

2026-10-01 01:41:28 (3,49 MB/s) - ‘count_1w.txt.1’ guardado [4956241/4956241]

--2026-10-01 01:41:28--  https://norvig.com/ngrams/count_2w.txt
Resolviendo norvig.com (norvig.com)... 158.106.138.13
Conectando con norvig.com (norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
Ubicación: https://www.norvig.com/ngrams/count_2w.txt [siguiente]
--2026-10-01 01:41:29--  https://www.norvig.com/ngrams/count_2w.txt
Resolviendo www.norvig.com (www.norvig.com)... 158.106.138.13
Conectando con www.norvig.com (www.norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 5566017 (5,3M) [text/plain]
Guardando como: ‘count_2w.txt.1’

count_2w.txt.1      100%[===================>]   5,31M  2,67MB/s    en 2,0s

2026-10-01 01:41:32 (2,67 MB/s) - ‘count_2w.txt.1’ guardado [5566017/5566017]

(333333, 2) (286358, 2)
Number of unigrams: 333333 Number of Bigrams: 286358

    unigram        count
0       the  23135851162
1        of  13151942776
2       and  12997637966
3        to  12136980858
4         a   9081174698
..      ...          ...
95     like    520585287
96  service    519537222
97        x    508609523
98     than    502609275
99     find    502043038

[100 rows x 2 columns]

               bigram   count
0    0Uplink verified  523545
1              0km to  116103
2            1000s of  939476
3             100s of  539389
4   100th anniversary  158621
..                ...     ...
95            24th of  327460
96   25th anniversary  261023
97            25th of  397735
98            26th of  271707
99            27th of  276619

[100 rows x 2 columns]

## Task 1.b

Complete the function below to compute the probability of a given sentence using the unigram and bigram counts from 1.a. Do not apply add-one smoothing

<b>Expected Output:</b>

```
sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = ?
unigram count for "i" = ?
bigramProbability for "i love" = ?

love you

bigram count for "love you" = ?
unigram count for "love" = ?
bigramProbability for "love you" = ?

sentenceProbability for "i love you" = ?

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = ?
unigram count for "i" = ?
bigramProbability for "i hate" = ?

hate you

bigram count for "hate you" = ?
unigram count for "hate" = ?
bigramProbability for "hate you" = ?

sentenceProbability for "i hate you" = ?

probability("i love you")>probability("i hate you") is: [True,False]?

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = ?
unigram count for "OOV1" = ?
bigramProbability for "OOV1 OOV2" = ?

sentenceProbability for "OOV1 OOV2" = ?
```

In [45]:
def probability(sentence):

    sentence_list = sentence.split(" ")
    
    # part of the expected output
    print(f"sentence= {sentence_list}\n")

    probabilities = []

    for i in range(0, len(sentence_list)-1):
        
        section = sentence_list[i] + " " +sentence_list[i+1]

        # part of the expected output
        print(section+"\n")

        # https://stackoverflow.com/questions/31536835/extract-value-from-single-row-of-pandas-dataframe
        bigram_count = bigrams_df.loc[bigrams_df['bigram'] == section]['count'].values
        unigram_count = unigrams_df.loc[unigrams_df['unigram'] == sentence_list[i]]['count'].values

        # I had to add logic to avoid errors when the words are not found in the txt files
        # https://stackoverflow.com/questions/5086178/how-to-check-if-array-is-not-empty
        bigram_count = bigram_count[0] if bigram_count.size else 0
        unigram_count = unigram_count[0] if unigram_count.size else 0
       
        print(f"bigram count for \"{section}\" = {bigram_count}")
        print(f"unigram count for \"{sentence_list[i]}\" = {unigram_count}")

        # https://youtu.be/UyC0bBiZY-A?t=16 P(w_i | w_i-1) = count(W_i-1, w_i) / count(W_i-1)
        bigram_probability = bigram_count / unigram_count if unigram_count != 0 else 0
        print(f"bigramProbability for \"{section}\" = {bigram_probability}\n")

        probabilities = probabilities + [bigram_probability]


    """
    Example from chapter 3, bigram
    P(<s> i want english food </s>) =   P(i|<s>)*P(want|i)*P(english|want)*P(food|english)*P(</s>|food)
                                    =   0.25*0.33*0.0011*0.5*0.68
                                    =   0.000031
    """
    sentence_probability = 1
    for probability in probabilities:
        sentence_probability = sentence_probability * probability
    print(f"sentenceProbability for \"{sentence}\" {sentence_probability}\n")
    return sentence_probability

#TESTING
probA = probability("i love you")
probB = probability('i hate you')
#probability("i love you")>probability("i hate you") is: [True,False]?
print(f'probability("i love you")>probability("i hate you") is: {probA>probB}\n')
probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = 3979312
unigram count for "i" = 3086225277
bigramProbability for "i love" = 0.001289378332053626

love you

bigram count for "love you" = 5428714
unigram count for "love" = 201063526
bigramProbability for "love you" = 0.02699999402178991

sentenceProbability for "i love you" 3.481320725727335e-05

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = 876611
unigram count for "i" = 3086225277
bigramProbability for "i hate" = 0.0002840398614232463

hate you

bigram count for "hate you" = 504048
unigram count for "hate" = 21274675
bigramProbability for "hate you" = 0.023692394830943365

sentenceProbability for "i hate you" 6.7295845445659906e-06

probability("i love you")>probability("i hate you") is: True

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = 0
unigram count for "OOV1" = 0
bigramProbability for "OOV1 OOV2" = 0

sentenceProbability for "OOV1 OOV2" 0

0

## Task 1.c

Copy the function from 1.b into a new code cell, and modify it such that it applies add-one smoothing. Your new function should also address the problem of underflow when computing a sentence Probability

In [67]:
"""
from the book:
3.6.1 Laplace Smoothing
The simplest way to do smoothing is to add one to all the n-gram counts, before we normalize them into probabilities. 

https://youtu.be/Hr6UWRwAIEQ?list=PLAUFqkTvH_MQ&t=73
"""

import math

def new_probability(sentence):
    """
    uses add one smoothing (also known as Laplace smoothing).
    The smoothing ensures no bigram will have a probability of zero.
    However, due to the mathematical nature of the interval [0, 1], 
    the probabilities of long sentences would underflow and become zero.
    To address the underflow, the function uses log. 
    """

    sentence_list = sentence.split(" ")
    
    # part of the expected output
    print(f"sentence= {sentence_list}\n")

    probabilities = []

    laplace_smoothing = 1
    V = len(unigrams_df)
    
    for i in range(0, len(sentence_list)-1):
        
        section = sentence_list[i] + " " +sentence_list[i+1]
       
        # part of the expected output
        print(section+"\n")

        # https://stackoverflow.com/questions/31536835/extract-value-from-single-row-of-pandas-dataframe
        bigram_count = bigrams_df.loc[bigrams_df['bigram'] == section]['count'].values
        unigram_count = unigrams_df.loc[unigrams_df['unigram'] == sentence_list[i]]['count'].values
        
        # I had to add logic to avoid errors when the words are not found in the txt files
        # https://stackoverflow.com/questions/5086178/how-to-check-if-array-is-not-empty
        bigram_count = bigram_count[0] if bigram_count.size else 0
        unigram_count = unigram_count[0] if unigram_count.size else 0
       
        print(f"bigram count for \"{section}\" = {bigram_count}")
        print(f"unigram count for \"{sentence_list[i]}\" = {unigram_count}")

        # P(w_i | w_i-1) = count(W_i-1, w_i) + 1 / count(W_i-1) + V (https://youtu.be/UyC0bBiZY-A?t=16)
        bigram_probability = (bigram_count + laplace_smoothing) / (unigram_count + V)
        print(f"bigramProbability for \"{section}\" = {bigram_probability}\n")

        probabilities = probabilities + [bigram_probability]

    # addressing underflow using log, instead of multiplying, we sum the log of the probabilities
    sentence_probability = 1
    sentence_log_probability = 0
    for probability in probabilities:
        sentence_probability = sentence_probability * probability
        sentence_log_probability = sentence_log_probability + math.log(probability)
    
    print(f"sentenceProbability for \"{sentence}\" {sentence_probability}")
    print(f"Log sentenceProbability for \"{sentence}\" {sentence_log_probability}")
    print(f"Does {sentence_probability} equals exp({sentence_log_probability})? {math.exp(sentence_log_probability)}\n")

    # even when it is possible to return the sentence probability, I'm still returning the log probability
    # it is the only way to avoid losing meaningful information when the probability is very small (underflow)
    return sentence_log_probability


#TESTING
probA = new_probability("i love you")
probB = new_probability('i hate you')
print(f'probability("i love you")>probability("i hate you") is: {probA>probB}\n')
new_probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = 3979312
unigram count for "i" = 3086225277
bigramProbability for "i love" = 0.001289239409583089

love you

bigram count for "love you" = 5428714
unigram count for "love" = 201063526
bigramProbability for "love you" = 0.026955311155076156

sentenceProbability for "i love you" 3.475184943869884e-05
Log sentenceProbability for "i love you" -10.267277766112153
Does 3.475184943869884e-05 equals exp(-10.267277766112153)? 3.4751849438698844e-05

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = 876611
unigram count for "i" = 3086225277
bigramProbability for "i hate" = 0.00028400951051436537

hate you

bigram count for "hate you" = 504048
unigram count for "hate" = 21274675
bigramProbability for "hate you" = 0.023326953599795038

sentenceProbability for "i hate you" 6.625076673669102e-06
Log sentenceProbability for "i hate you" -11.924648612774943
Does 6.625076673669102e-06 equals exp(-11.924648612774943)? 6.625076673669107e-06

probability("i love you")>probability("i hate you") is: True

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = 0
unigram count for "OOV1" = 0
bigramProbability for "OOV1 OOV2" = 3.000003000003e-06

sentenceProbability for "OOV1 OOV2" 3.000003000003e-06
Log sentenceProbability for "OOV1 OOV2" -12.716897269295664
Does 3.000003000003e-06 equals exp(-12.716897269295664)? 3.000003000003e-06

-12.716897269295664

Remember that with <code>log</code> representing the natural logarithm function and <code>exp</code> representing the exponential function, this is true: $exp(log(X) = X$

To further showcase the importance underflow handling I'll use a 'long' sentence from 'One Hundred Years of Solitude' by Gabriel García Márquez.

In [64]:
probability("At the beginning of the road into the swamp they put up a sign that said MACONDO and another larger one on the main street that said GOD EXISTS. In all the houses keys to memorizing objects and feelings had been written. But the system demanded so much vigilance and moral strength that many succumbed to the spell of an imaginary reality, one invented by themselves, which was less practical for them but more comforting. Pilar Ternera was the one who contributed most to popularize that mystification when she conceived the trick of reading the past in cards as she had read the future before.")

sentence= ['At', 'the', 'beginning', 'of', 'the', 'road', 'into', 'the', 'swamp', 'they', 'put', 'up', 'a', 'sign', 'that', 'said', 'MACONDO', 'and', 'another', 'larger', 'one', 'on', 'the', 'main', 'street', 'that', 'said', 'GOD', 'EXISTS.', 'In', 'all', 'the', 'houses', 'keys', 'to', 'memorizing', 'objects', 'and', 'feelings', 'had', 'been', 'written.', 'But', 'the', 'system', 'demanded', 'so', 'much', 'vigilance', 'and', 'moral', 'strength', 'that', 'many', 'succumbed', 'to', 'the', 'spell', 'of', 'an', 'imaginary', 'reality,', 'one', 'invented', 'by', 'themselves,', 'which', 'was', 'less', 'practical', 'for', 'them', 'but', 'more', 'comforting.', 'Pilar', 'Ternera', 'was', 'the', 'one', 'who', 'contributed', 'most', 'to', 'popularize', 'that', 'mystification', 'when', 'she', 'conceived', 'the', 'trick', 'of', 'reading', 'the', 'past', 'in', 'cards', 'as', 'she', 'had', 'read', 'the', 'future', 'before.']

At the

bigram count for "At the" = 33188535
unigram count for "At" = 0
bigramProbability for "At the" = 0

the beginning

bigram count for "the beginning" = 18127480
unigram count for "the" = 23135851162
bigramProbability for "the beginning" = 0.0007835233669627806

beginning of

bigram count for "beginning of" = 13625517
unigram count for "beginning" = 49148844
bigramProbability for "beginning of" = 0.277229653661844

of the

bigram count for "of the" = 2766332391
unigram count for "of" = 13151942776
bigramProbability for "of the" = 0.21033640718450158

the road

bigram count for "the road" = 15141988
unigram count for "the" = 23135851162
bigramProbability for "the road" = 0.0006544815617101782

road into

bigram count for "road into" = 0
unigram count for "road" = 131800620
bigramProbability for "road into" = 0.0

into the

bigram count for "into the" = 119750246
unigram count for "into" = 445315294
bigramProbability for "into the" = 0.26891114590822923

the swamp

bigram count for "the swamp" = 205418
unigram count for "the" = 23135851162
bigramProbability for "the swamp" = 8.878774269493635e-06

swamp they

bigram count for "swamp they" = 0
unigram count for "swamp" = 2575587
bigramProbability for "swamp they" = 0.0

they put

bigram count for "they put" = 1231279
unigram count for "they" = 883223816
bigramProbability for "they put" = 0.001394073594591566

put up

bigram count for "put up" = 3667761
unigram count for "put" = 115205090
bigramProbability for "put up" = 0.031836796447101426

up a

bigram count for "up a" = 22678765
unigram count for "up" = 829969374
bigramProbability for "up a" = 0.027324821506004147

a sign

bigram count for "a sign" = 3490172
unigram count for "a" = 9081174698
bigramProbability for "a sign" = 0.0003843304546017225

sign that

bigram count for "sign that" = 1190974
unigram count for "sign" = 242290578
bigramProbability for "sign that" = 0.004915477976200957

that said

bigram count for "that said" = 1516362
unigram count for "that" = 3400031103
bigramProbability for "that said" = 0.0004459847436872109

said MACONDO

bigram count for "said MACONDO" = 0
unigram count for "said" = 315595259
bigramProbability for "said MACONDO" = 0.0

MACONDO and

bigram count for "MACONDO and" = 0
unigram count for "MACONDO" = 0
bigramProbability for "MACONDO and" = 0

and another

bigram count for "and another" = 5565304
unigram count for "and" = 12997637966
bigramProbability for "and another" = 0.00042817810548024615

another larger

bigram count for "another larger" = 0
unigram count for "another" = 192535750
bigramProbability for "another larger" = 0.0

larger one

bigram count for "larger one" = 132829
unigram count for "larger" = 61265757
bigramProbability for "larger one" = 0.002168078980889765

one on

bigram count for "one on" = 3332009
unigram count for "one" = 993536631
bigramProbability for "one on" = 0.0033536851043391475

on the

bigram count for "on the" = 800328815
unigram count for "on" = 3750423199
bigramProbability for "on the" = 0.21339693483481995

the main

bigram count for "the main" = 30871717
unigram count for "the" = 23135851162
bigramProbability for "the main" = 0.0013343670299325726

main street

bigram count for "main street" = 428235
unigram count for "main" = 199616754
bigramProbability for "main street" = 0.002145285861125665

street that

bigram count for "street that" = 134718
unigram count for "street" = 149130754
bigramProbability for "street that" = 0.0009033549176583657

that said

bigram count for "that said" = 1516362
unigram count for "that" = 3400031103
bigramProbability for "that said" = 0.0004459847436872109

said GOD

bigram count for "said GOD" = 0
unigram count for "said" = 315595259
bigramProbability for "said GOD" = 0.0

GOD EXISTS.

bigram count for "GOD EXISTS." = 0
unigram count for "GOD" = 0
bigramProbability for "GOD EXISTS." = 0

EXISTS. In

bigram count for "EXISTS. In" = 0
unigram count for "EXISTS." = 0
bigramProbability for "EXISTS. In" = 0

In all

bigram count for "In all" = 3740307
unigram count for "In" = 0
bigramProbability for "In all" = 0

all the

bigram count for "all the" = 129776996
unigram count for "all" = 2022459848
bigramProbability for "all the" = 0.06416789738908082

the houses

bigram count for "the houses" = 871517
unigram count for "the" = 23135851162
bigramProbability for "the houses" = 3.7669545585227605e-05

houses keys

bigram count for "houses keys" = 0
unigram count for "houses" = 29896478
bigramProbability for "houses keys" = 0.0

keys to

bigram count for "keys to" = 1361387
unigram count for "keys" = 23716024
bigramProbability for "keys to" = 0.057403677783426095

to memorizing

bigram count for "to memorizing" = 0
unigram count for "to" = 12136980858
bigramProbability for "to memorizing" = 0.0

memorizing objects

bigram count for "memorizing objects" = 0
unigram count for "memorizing" = 303288
bigramProbability for "memorizing objects" = 0.0

objects and

bigram count for "objects and" = 1406890
unigram count for "objects" = 33845165
bigramProbability for "objects and" = 0.041568419004605235

and feelings

bigram count for "and feelings" = 757321
unigram count for "and" = 12997637966
bigramProbability for "and feelings" = 5.8266048183604256e-05

feelings had

bigram count for "feelings had" = 0
unigram count for "feelings" = 11299333
bigramProbability for "feelings had" = 0.0

had been

bigram count for "had been" = 47463128
unigram count for "had" = 480232730
bigramProbability for "had been" = 0.09883359678545858

been written.

bigram count for "been written." = 0
unigram count for "been" = 575019382
bigramProbability for "been written." = 0.0

written. But

bigram count for "written. But" = 0
unigram count for "written." = 0
bigramProbability for "written. But" = 0

But the

bigram count for "But the" = 17157400
unigram count for "But" = 0
bigramProbability for "But the" = 0

the system

bigram count for "the system" = 28246387
unigram count for "the" = 23135851162
bigramProbability for "the system" = 0.0012208924928767658

system demanded

bigram count for "system demanded" = 0
unigram count for "system" = 396975018
bigramProbability for "system demanded" = 0.0

demanded so

bigram count for "demanded so" = 0
unigram count for "demanded" = 3531986
bigramProbability for "demanded so" = 0.0

so much

bigram count for "so much" = 26148179
unigram count for "so" = 661809559
bigramProbability for "so much" = 0.039510125903152754

much vigilance

bigram count for "much vigilance" = 0
unigram count for "much" = 242326300
bigramProbability for "much vigilance" = 0.0

vigilance and

bigram count for "vigilance and" = 0
unigram count for "vigilance" = 801669
bigramProbability for "vigilance and" = 0.0

and moral

bigram count for "and moral" = 974839
unigram count for "and" = 12997637966
bigramProbability for "and moral" = 7.500124272964382e-05

moral strength

bigram count for "moral strength" = 0
unigram count for "moral" = 13643598
bigramProbability for "moral strength" = 0.0

strength that

bigram count for "strength that" = 159626
unigram count for "strength" = 28148438
bigramProbability for "strength that" = 0.005670865289221377

that many

bigram count for "that many" = 7722065
unigram count for "that" = 3400031103
bigramProbability for "that many" = 0.0022711748116617156

many succumbed

bigram count for "many succumbed" = 0
unigram count for "many" = 318966441
bigramProbability for "many succumbed" = 0.0

succumbed to

bigram count for "succumbed to" = 293580
unigram count for "succumbed" = 365526
bigramProbability for "succumbed to" = 0.803171320234402

to the

bigram count for "to the" = 1139248999
unigram count for "to" = 12136980858
bigramProbability for "to the" = 0.09386593027779826

the spell

bigram count for "the spell" = 559324
unigram count for "the" = 23135851162
bigramProbability for "the spell" = 2.417563962023901e-05

spell of

bigram count for "spell of" = 238424
unigram count for "spell" = 8506049
bigramProbability for "spell of" = 0.02802993493218767

of an

bigram count for "of an" = 76105830
unigram count for "of" = 13151942776
bigramProbability for "of an" = 0.005786660670306433

an imaginary

bigram count for "an imaginary" = 348447
unigram count for "an" = 1518266684
bigramProbability for "an imaginary" = 0.00022950315887982693

imaginary reality,

bigram count for "imaginary reality," = 0
unigram count for "imaginary" = 2348396
bigramProbability for "imaginary reality," = 0.0

reality, one

bigram count for "reality, one" = 0
unigram count for "reality," = 0
bigramProbability for "reality, one" = 0

one invented

bigram count for "one invented" = 0
unigram count for "one" = 993536631
bigramProbability for "one invented" = 0.0

invented by

bigram count for "invented by" = 411748
unigram count for "invented" = 3607460
bigramProbability for "invented by" = 0.11413792529924102

by themselves,

bigram count for "by themselves," = 0
unigram count for "by" = 3350048871
bigramProbability for "by themselves," = 0.0

themselves, which

bigram count for "themselves, which" = 0
unigram count for "themselves," = 0
bigramProbability for "themselves, which" = 0

which was

bigram count for "which was" = 24575277
unigram count for "which" = 810514085
bigramProbability for "which was" = 0.03032060448400474

was less

bigram count for "was less" = 1378815
unigram count for "was" = 1483428678
bigramProbability for "was less" = 0.0009294784578783773

less practical

bigram count for "less practical" = 0
unigram count for "less" = 145430147
bigramProbability for "less practical" = 0.0

practical for

bigram count for "practical for" = 182370
unigram count for "practical" = 29138914
bigramProbability for "practical for" = 0.006258640936309431

for them

bigram count for "for them" = 14410193
unigram count for "for" = 5933321709
bigramProbability for "for them" = 0.0024286889716668824

them but

bigram count for "them but" = 806299
unigram count for "them" = 403000411
bigramProbability for "them but" = 0.002000739895027055

but more

bigram count for "but more" = 2349849
unigram count for "but" = 999899654
bigramProbability for "but more" = 0.0023500848216115094

more comforting.

bigram count for "more comforting." = 0
unigram count for "more" = 1544771673
bigramProbability for "more comforting." = 0.0

comforting. Pilar

bigram count for "comforting. Pilar" = 0
unigram count for "comforting." = 0
bigramProbability for "comforting. Pilar" = 0

Pilar Ternera

bigram count for "Pilar Ternera" = 0
unigram count for "Pilar" = 0
bigramProbability for "Pilar Ternera" = 0

Ternera was

bigram count for "Ternera was" = 0
unigram count for "Ternera" = 0
bigramProbability for "Ternera was" = 0

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.04428542805884733

the one

bigram count for "the one" = 29220776
unigram count for "the" = 23135851162
bigramProbability for "the one" = 0.0012630084709394362

one who

bigram count for "one who" = 6641284
unigram count for "one" = 993536631
bigramProbability for "one who" = 0.006684488314553145

who contributed

bigram count for "who contributed" = 351158
unigram count for "who" = 630927278
bigramProbability for "who contributed" = 0.0005565744456526732

contributed most

bigram count for "contributed most" = 0
unigram count for "contributed" = 13454831
bigramProbability for "contributed most" = 0.0

most to

bigram count for "most to" = 553499
unigram count for "most" = 416210411
bigramProbability for "most to" = 0.0013298538080057782

to popularize

bigram count for "to popularize" = 0
unigram count for "to" = 12136980858
bigramProbability for "to popularize" = 0.0

popularize that

bigram count for "popularize that" = 0
unigram count for "popularize" = 84779
bigramProbability for "popularize that" = 0.0

that mystification

bigram count for "that mystification" = 0
unigram count for "that" = 3400031103
bigramProbability for "that mystification" = 0.0

mystification when

bigram count for "mystification when" = 0
unigram count for "mystification" = 39689
bigramProbability for "mystification when" = 0.0

when she

bigram count for "when she" = 8784206
unigram count for "when" = 650621178
bigramProbability for "when she" = 0.013501260483100967

she conceived

bigram count for "she conceived" = 0
unigram count for "she" = 339171382
bigramProbability for "she conceived" = 0.0

conceived the

bigram count for "conceived the" = 113944
unigram count for "conceived" = 2818126
bigramProbability for "conceived the" = 0.04043254276068565

the trick

bigram count for "the trick" = 1002858
unigram count for "the" = 23135851162
bigramProbability for "the trick" = 4.334649254863667e-05

trick of

bigram count for "trick of" = 199472
unigram count for "trick" = 8208473
bigramProbability for "trick of" = 0.02430074387769808

of reading

bigram count for "of reading" = 2041821
unigram count for "of" = 13151942776
bigramProbability for "of reading" = 0.00015524862256289368

reading the

bigram count for "reading the" = 3790780
unigram count for "reading" = 95289449
bigramProbability for "reading the" = 0.03978173910943698

the past

bigram count for "the past" = 42455167
unigram count for "the" = 23135851162
bigramProbability for "the past" = 0.0018350380412946053

past in

bigram count for "past in" = 303612
unigram count for "past" = 105625616
bigramProbability for "past in" = 0.0028744163726344566

in cards

bigram count for "in cards" = 0
unigram count for "in" = 8469404971
bigramProbability for "in cards" = 0.0

cards as

bigram count for "cards as" = 209461
unigram count for "cards" = 121094522
bigramProbability for "cards as" = 0.0017297314241844896

as she

bigram count for "as she" = 8915662
unigram count for "as" = 2247431740
bigramProbability for "as she" = 0.0039670446231216796

she had

bigram count for "she had" = 11164703
unigram count for "she" = 339171382
bigramProbability for "she had" = 0.03291758559983696

had read

bigram count for "had read" = 626958
unigram count for "had" = 480232730
bigramProbability for "had read" = 0.0013055295085780596

read the

bigram count for "read the" = 20535201
unigram count for "read" = 322331766
bigramProbability for "read the" = 0.06370827565285637

the future

bigram count for "the future" = 31618324
unigram count for "the" = 23135851162
bigramProbability for "the future" = 0.0013666375954186733

future before.

bigram count for "future before." = 0
unigram count for "future" = 121844371
bigramProbability for "future before." = 0.0

sentenceProbability for "At the beginning of the road into the swamp they put up a sign that said MACONDO and another larger one on the main street that said GOD EXISTS. In all the houses keys to memorizing objects and feelings had been written. But the system demanded so much vigilance and moral strength that many succumbed to the spell of an imaginary reality, one invented by themselves, which was less practical for them but more comforting. Pilar Ternera was the one who contributed most to popularize that mystification when she conceived the trick of reading the past in cards as she had read the future before." 0.0

np.float64(0.0)

The book explains: "Multiplying enough n-grams together would result in numerical underflow. Adding in log space is equivalent to multiplying in linear space, so we combine log probabilities by adding them." (section '3.1.3 Dealing with scale in large n-gram models')

See the same sentence with a log probability:

In [65]:
#I need to test underflow, the core material suggests using log
new_probability("At the beginning of the road into the swamp they put up a sign that said MACONDO and another larger one on the main street that said GOD EXISTS. In all the houses keys to memorizing objects and feelings had been written. But the system demanded so much vigilance and moral strength that many succumbed to the spell of an imaginary reality, one invented by themselves, which was less practical for them but more comforting. Pilar Ternera was the one who contributed most to popularize that mystification when she conceived the trick of reading the past in cards as she had read the future before.")

sentence= ['At', 'the', 'beginning', 'of', 'the', 'road', 'into', 'the', 'swamp', 'they', 'put', 'up', 'a', 'sign', 'that', 'said', 'MACONDO', 'and', 'another', 'larger', 'one', 'on', 'the', 'main', 'street', 'that', 'said', 'GOD', 'EXISTS.', 'In', 'all', 'the', 'houses', 'keys', 'to', 'memorizing', 'objects', 'and', 'feelings', 'had', 'been', 'written.', 'But', 'the', 'system', 'demanded', 'so', 'much', 'vigilance', 'and', 'moral', 'strength', 'that', 'many', 'succumbed', 'to', 'the', 'spell', 'of', 'an', 'imaginary', 'reality,', 'one', 'invented', 'by', 'themselves,', 'which', 'was', 'less', 'practical', 'for', 'them', 'but', 'more', 'comforting.', 'Pilar', 'Ternera', 'was', 'the', 'one', 'who', 'contributed', 'most', 'to', 'popularize', 'that', 'mystification', 'when', 'she', 'conceived', 'the', 'trick', 'of', 'reading', 'the', 'past', 'in', 'cards', 'as', 'she', 'had', 'read', 'the', 'future', 'before.']

At the

bigram count for "At the" = 33188535
unigram count for "At" = 0
bigramProbability for "At the" = 99.56570756570757

the beginning

bigram count for "the beginning" = 18127480
unigram count for "the" = 23135851162
bigramProbability for "the beginning" = 0.0007835121216256535

beginning of

bigram count for "beginning of" = 13625517
unigram count for "beginning" = 49148844
bigramProbability for "beginning of" = 0.27536213695690875

of the

bigram count for "of the" = 2766332391
unigram count for "of" = 13151942776
bigramProbability for "of the" = 0.2103310764672147

the road

bigram count for "the road" = 15141988
unigram count for "the" = 23135851162
bigramProbability for "the road" = 0.0006544721755340583

road into

bigram count for "road into" = 0
unigram count for "road" = 131800620
bigramProbability for "road into" = 7.568077525085472e-09

into the

bigram count for "into the" = 119750246
unigram count for "into" = 445315294
bigramProbability for "into the" = 0.26871000996038075

the swamp

bigram count for "the swamp" = 205418
unigram count for "the" = 23135851162
bigramProbability for "the swamp" = 8.878689571497558e-06

swamp they

bigram count for "swamp they" = 0
unigram count for "swamp" = 2575587
bigramProbability for "swamp they" = 3.437701964990443e-07

they put

bigram count for "they put" = 1231279
unigram count for "they" = 883223816
bigramProbability for "they put" = 0.0013935487946575371

put up

bigram count for "put up" = 3667761
unigram count for "put" = 115205090
bigramProbability for "put up" = 0.03174495466326384

up a

bigram count for "up a" = 22678765
unigram count for "up" = 829969374
bigramProbability for "up a" = 0.027313852898229803

a sign

bigram count for "a sign" = 3490172
unigram count for "a" = 9081174698
bigramProbability for "a sign" = 0.00038431645802505375

sign that

bigram count for "sign that" = 1190974
unigram count for "sign" = 242290578
bigramProbability for "sign that" = 0.00490872888451625

that said

bigram count for "that said" = 1516362
unigram count for "that" = 3400031103
bigramProbability for "that said" = 0.00044594131850872

said MACONDO

bigram count for "said MACONDO" = 0
unigram count for "said" = 315595259
bigramProbability for "said MACONDO" = 3.1652722334165942e-09

MACONDO and

bigram count for "MACONDO and" = 0
unigram count for "MACONDO" = 0
bigramProbability for "MACONDO and" = 3.000003000003e-06

and another

bigram count for "and another" = 5565304
unigram count for "and" = 12997637966
bigramProbability for "and another" = 0.00042816720178695636

another larger

bigram count for "another larger" = 0
unigram count for "another" = 192535750
bigramProbability for "another larger" = 5.184864180642162e-09

larger one

bigram count for "larger one" = 132829
unigram count for "larger" = 61265757
bigramProbability for "larger one" = 0.0021563630241940262

one on

bigram count for "one on" = 3332009
unigram count for "one" = 993536631
bigramProbability for "one on" = 0.003352561321593576

on the

bigram count for "on the" = 800328815
unigram count for "on" = 3750423199
bigramProbability for "on the" = 0.2133779703299601

the main

bigram count for "the main" = 30871717
unigram count for "the" = 23135851162
bigramProbability for "the main" = 0.0013343478483529442

main street

bigram count for "main street" = 428235
unigram count for "main" = 199616754
bigramProbability for "main street" = 0.0021417144969784383

street that

bigram count for "street that" = 134718
unigram count for "street" = 149130754
bigramProbability for "street that" = 0.0009013469570118205

that said

bigram count for "that said" = 1516362
unigram count for "that" = 3400031103
bigramProbability for "that said" = 0.00044594131850872

said GOD

bigram count for "said GOD" = 0
unigram count for "said" = 315595259
bigramProbability for "said GOD" = 3.1652722334165942e-09

GOD EXISTS.

bigram count for "GOD EXISTS." = 0
unigram count for "GOD" = 0
bigramProbability for "GOD EXISTS." = 3.000003000003e-06

EXISTS. In

bigram count for "EXISTS. In" = 0
unigram count for "EXISTS." = 0
bigramProbability for "EXISTS. In" = 3.000003000003e-06

In all

bigram count for "In all" = 3740307
unigram count for "In" = 0
bigramProbability for "In all" = 11.220935220935221

all the

bigram count for "all the" = 129776996
unigram count for "all" = 2022459848
bigramProbability for "all the" = 0.06415732375360425

the houses

bigram count for "the houses" = 871517
unigram count for "the" = 23135851162
bigramProbability for "the houses" = 3.76690460861576e-05

houses keys

bigram count for "houses keys" = 0
unigram count for "houses" = 29896478
bigramProbability for "houses keys" = 3.307992894828221e-08

keys to

bigram count for "keys to" = 1361387
unigram count for "keys" = 23716024
bigramProbability for "keys to" = 0.056608083118396886

to memorizing

bigram count for "to memorizing" = 0
unigram count for "to" = 12136980858
bigramProbability for "to memorizing" = 8.239055068225184e-11

memorizing objects

bigram count for "memorizing objects" = 0
unigram count for "memorizing" = 303288
bigramProbability for "memorizing objects" = 1.5707932977391572e-06

objects and

bigram count for "objects and" = 1406890
unigram count for "objects" = 33845165
bigramProbability for "objects and" = 0.04116304350179461

and feelings

bigram count for "and feelings" = 757321
unigram count for "and" = 12997637966
bigramProbability for "and feelings" = 5.8264630885764816e-05

feelings had

bigram count for "feelings had" = 0
unigram count for "feelings" = 11299333
bigramProbability for "feelings had" = 8.596481666369515e-08

had been

bigram count for "had been" = 47463128
unigram count for "had" = 480232730
bigramProbability for "had been" = 0.09876504533779365

been written.

bigram count for "been written." = 0
unigram count for "been" = 575019382
bigramProbability for "been written." = 1.7380642759285493e-09

written. But

bigram count for "written. But" = 0
unigram count for "written." = 0
bigramProbability for "written. But" = 3.000003000003e-06

But the

bigram count for "But the" = 17157400
unigram count for "But" = 0
bigramProbability for "But the" = 51.47225447225447

the system

bigram count for "the system" = 28246387
unigram count for "the" = 23135851162
bigramProbability for "the system" = 0.00122087494617379

system demanded

bigram count for "system demanded" = 0
unigram count for "system" = 396975018
bigramProbability for "system demanded" = 2.516936775889717e-09

demanded so

bigram count for "demanded so" = 0
unigram count for "demanded" = 3531986
bigramProbability for "demanded so" = 2.587108593107063e-07

so much

bigram count for "so much" = 26148179
unigram count for "so" = 661809559
bigramProbability for "so much" = 0.03949023740331868

much vigilance

bigram count for "much vigilance" = 0
unigram count for "much" = 242326300
bigramProbability for "much vigilance" = 4.120998567569745e-09

vigilance and

bigram count for "vigilance and" = 0
unigram count for "vigilance" = 801669
bigramProbability for "vigilance and" = 8.810557162013811e-07

and moral

bigram count for "and moral" = 974839
unigram count for "and" = 12997637966
bigramProbability for "and moral" = 7.499939625770672e-05

moral strength

bigram count for "moral strength" = 0
unigram count for "moral" = 13643598
bigramProbability for "moral strength" = 7.154646467096389e-08

strength that

bigram count for "strength that" = 159626
unigram count for "strength" = 28148438
bigramProbability for "strength that" = 0.005604532105816032

that many

bigram count for "that many" = 7722065
unigram count for "that" = 3400031103
bigramProbability for "that many" = 0.0022709524656374215

many succumbed

bigram count for "many succumbed" = 0
unigram count for "many" = 318966441
bigramProbability for "many succumbed" = 3.131853140616379e-09

succumbed to

bigram count for "succumbed to" = 293580
unigram count for "succumbed" = 365526
bigramProbability for "succumbed to" = 0.4200861690269425

to the

bigram count for "to the" = 1139248999
unigram count for "to" = 12136980858
bigramProbability for "to the" = 0.09386335247420473

the spell

bigram count for "the spell" = 559324
unigram count for "the" = 23135851162
bigramProbability for "the spell" = 2.417533453369879e-05

spell of

bigram count for "spell of" = 238424
unigram count for "spell" = 8506049
bigramProbability for "spell of" = 0.02697303951792105

of an

bigram count for "of an" = 76105830
unigram count for "of" = 13151942776
bigramProbability for "of an" = 0.005786514088456626

an imaginary

bigram count for "an imaginary" = 348447
unigram count for "an" = 1518266684
bigramProbability for "an imaginary" = 0.0002294534413929221

imaginary reality,

bigram count for "imaginary reality," = 0
unigram count for "imaginary" = 2348396
bigramProbability for "imaginary reality," = 3.728937562296563e-07

reality, one

bigram count for "reality, one" = 0
unigram count for "reality," = 0
bigramProbability for "reality, one" = 3.000003000003e-06

one invented

bigram count for "one invented" = 0
unigram count for "one" = 993536631
bigramProbability for "one invented" = 1.0061678451125825e-09

invented by

bigram count for "invented by" = 411748
unigram count for "invented" = 3607460
bigramProbability for "invented by" = 0.1044837929827829

by themselves,

bigram count for "by themselves," = 0
unigram count for "by" = 3350048871
bigramProbability for "by themselves," = 2.984734096325208e-10

themselves, which

bigram count for "themselves, which" = 0
unigram count for "themselves," = 0
bigramProbability for "themselves, which" = 3.000003000003e-06

which was

bigram count for "which was" = 24575277
unigram count for "which" = 810514085
bigramProbability for "which was" = 0.030308141155109408

was less

bigram count for "was less" = 1378815
unigram count for "was" = 1483428678
bigramProbability for "was less" = 0.0009292703208317954

less practical

bigram count for "less practical" = 0
unigram count for "less" = 145430147
bigramProbability for "less practical" = 6.860428963413881e-09

practical for

bigram count for "practical for" = 182370
unigram count for "practical" = 29138914
bigramProbability for "practical for" = 0.0061878892369489165

for them

bigram count for "for them" = 14410193
unigram count for "for" = 5933321709
bigramProbability for "for them" = 0.002428552704530477

them but

bigram count for "them but" = 806299
unigram count for "them" = 403000411
bigramProbability for "them but" = 0.001999088873654965

but more

bigram count for "but more" = 2349849
unigram count for "but" = 999899654
bigramProbability for "but more" = 0.0023493026430251094

more comforting.

bigram count for "more comforting." = 0
unigram count for "more" = 1544771673
bigramProbability for "more comforting." = 6.472052036054306e-10

comforting. Pilar

bigram count for "comforting. Pilar" = 0
unigram count for "comforting." = 0
bigramProbability for "comforting. Pilar" = 3.000003000003e-06

Pilar Ternera

bigram count for "Pilar Ternera" = 0
unigram count for "Pilar" = 0
bigramProbability for "Pilar Ternera" = 3.000003000003e-06

Ternera was

bigram count for "Ternera was" = 0
unigram count for "Ternera" = 0
bigramProbability for "Ternera was" = 3.000003000003e-06

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the one

bigram count for "the one" = 29220776
unigram count for "the" = 23135851162
bigramProbability for "the one" = 0.0012629903174533792

one who

bigram count for "one who" = 6641284
unigram count for "one" = 993536631
bigramProbability for "one who" = 0.006682247417228518

who contributed

bigram count for "who contributed" = 351158
unigram count for "who" = 630927278
bigramProbability for "who contributed" = 0.0005562821343212241

contributed most

bigram count for "contributed most" = 0
unigram count for "contributed" = 13454831
bigramProbability for "contributed most" = 7.252597227593173e-08

most to

bigram count for "most to" = 553499
unigram count for "most" = 416210411
bigramProbability for "most to" = 0.0013287920127783746

to popularize

bigram count for "to popularize" = 0
unigram count for "to" = 12136980858
bigramProbability for "to popularize" = 8.239055068225184e-11

popularize that

bigram count for "popularize that" = 0
unigram count for "popularize" = 84779
bigramProbability for "popularize that" = 2.391703658349916e-06

that mystification

bigram count for "that mystification" = 0
unigram count for "that" = 3400031103
bigramProbability for "that mystification" = 2.94086124832062e-10

mystification when

bigram count for "mystification when" = 0
unigram count for "mystification" = 39689
bigramProbability for "mystification when" = 2.680807030148356e-06

when she

bigram count for "when she" = 8784206
unigram count for "when" = 650621178
bigramProbability for "when she" = 0.013494348455325475

she conceived

bigram count for "she conceived" = 0
unigram count for "she" = 339171382
bigramProbability for "she conceived" = 2.9454671932906736e-09

conceived the

bigram count for "conceived the" = 113944
unigram count for "conceived" = 2818126
bigramProbability for "conceived the" = 0.03615626920737347

the trick

bigram count for "the trick" = 1002858
unigram count for "the" = 23135851162
bigramProbability for "the trick" = 4.334591125934052e-05

trick of

bigram count for "trick of" = 199472
unigram count for "trick" = 8208473
bigramProbability for "trick of" = 0.02335255565392143

of reading

bigram count for "of reading" = 2041821
unigram count for "of" = 13151942776
bigramProbability for "of reading" = 0.0001552447639540351

reading the

bigram count for "reading the" = 3790780
unigram count for "reading" = 95289449
bigramProbability for "reading the" = 0.03964307376039321

the past

bigram count for "the past" = 42455167
unigram count for "the" = 23135851162
bigramProbability for "the past" = 0.0018350116463315314

past in

bigram count for "past in" = 303612
unigram count for "past" = 105625616
bigramProbability for "past in" = 0.0028653832721575977

in cards

bigram count for "in cards" = 0
unigram count for "in" = 8469404971
bigramProbability for "in cards" = 1.1806740233375693e-10

cards as

bigram count for "cards as" = 209461
unigram count for "cards" = 121094522
bigramProbability for "cards as" = 0.0017249913539195763

as she

bigram count for "as she" = 8915662
unigram count for "as" = 2247431740
bigramProbability for "as she" = 0.003966456773928171

she had

bigram count for "she had" = 11164703
unigram count for "she" = 339171382
bigramProbability for "she had" = 0.032885269354801155

had read

bigram count for "had read" = 626958
unigram count for "had" = 480232730
bigramProbability for "had read" = 0.0013046260405616698

read the

bigram count for "read the" = 20535201
unigram count for "read" = 322331766
bigramProbability for "read the" = 0.06364246416374893

the future

bigram count for "the future" = 31618324
unigram count for "the" = 23135851162
bigramProbability for "the future" = 0.0013666179489030738

future before.

bigram count for "future before." = 0
unigram count for "future" = 121844371
bigramProbability for "future before." = 8.184799413156429e-09

sentenceProbability for "At the beginning of the road into the swamp they put up a sign that said MACONDO and another larger one on the main street that said GOD EXISTS. In all the houses keys to memorizing objects and feelings had been written. But the system demanded so much vigilance and moral strength that many succumbed to the spell of an imaginary reality, one invented by themselves, which was less practical for them but more comforting. Pilar Ternera was the one who contributed most to popularize that mystification when she conceived the trick of reading the past in cards as she had read the future before." 0.0

Log sentenceProbability for "At the beginning of the road into the swamp they put up a sign that said MACONDO and another larger one on the main street that said GOD EXISTS. In all the houses keys to memorizing objects and feelings had been written. But the system demanded so much vigilance and moral strength that many succumbed to the spell of an imaginary reality, one invented by themselves, which was less practical for them but more comforting. Pilar Ternera was the one who contributed most to popularize that mystification when she conceived the trick of reading the past in cards as she had read the future before." -983.8231045199174

-983.8231045199174

In this case, instead of having a probability of zero, we have the log of the probability. This allows to extrapolate relationships and comparisons using negative numbers.

# Task 2

Using the [bigram counts](https://www.norvig.com/ngrams/count_2w.txt) (bigrams_df), write a function that implements the Shannon visualisation method:

<!--<b>Expected Output:</b>-->

```
<s> I
    I want
        want to
             to eat
                eat Chinese
                    Chinese food
                            food </s>

I want to eat Chinese food
```

[Chapter 3, section 3.4](https://web.stanford.edu/~jurafsky/slp3/3.pdf) gives a detailed description of the Shannon Visualisation method; a screenshot of this section is provided below. If you can follow the logic applied to unigrams, then you should be able to apply the same logic to bigrams.

Note: given the large size of the bigrams data, the Shannon Visualisation sampling can continue for a long time; therefore, for initial testing, you could terminate the sampling early whenever a common word (e.g. “and”) is generated as the next new seed.

Extra Help: 
- The seed word can be any word, but let's stick to the default seed word `<S>`, which indicates the beginning of the sentence. 
- First, you need to retrieve a list of all the bigrams starting with `<S>`, and then <u>randomly select one of them according to its probability</u>. Understanding this last part is key! You have a probability space between 0 and 1, and each of the candidate bigrams covers <u>an interval in this space proportional to its frequency</u>. For example, the candidate bigram “`<S>` and” has a total frequency of 261891475, which translates to a probability of 0.031513. If you consider this bigram to be your first candidate, then you can assign the probability interval 0.0 to 0.031513 to it. There are 8640 bigrams in the dataset which start with `<S>` and you need to compute the probability intervals for all of them. 
- Then generate a random number between 0 and 1 and check to see which interval it falls into; that would be your chosen bigram.
- Pick the second word in the chosen bigram, and that would be your new seed word.
- This process should be repeated until you either reach `</S>` (indicating the end of the sentence) or come across a seed which does not exist in your list of bigrams (i.e. there is no bigram starting with this seed word).

In [ ]:
import random

def ShannonVisualization(full_sentence="", seed="<S>"):

    # this is never going to happen because </S> is not part of the e-tivity corpus
    # however, other datasets may have it since it is a common practice to use it as the ending token
    if seed == "</S>":
        return full_sentence
    
    # get all the bigrams starting with the seed word
    bigrams_starting_with_seed_word_df = bigrams_df.loc[bigrams_df['bigram'].str.contains("^" + seed + " ")]
    
    # resetting the index to avoid any confusions (not sure if this is the best way to go or adding a table and appending the probability to each row would be better)
    bigrams_starting_with_seed_word_df = bigrams_starting_with_seed_word_df.reset_index()

    # this will hold the sum of all bigrams' counts with the seed word
    full_count = 0
    for index, row in bigrams_starting_with_seed_word_df.iterrows():
        full_count = full_count + row['count']

    if full_count == 0:
        # a seed which does not exist in your list of bigrams (i.e. there is no bigram starting with this seed word).
        return full_sentence

    probabilities = []

    for index, row in bigrams_starting_with_seed_word_df.iterrows():
        probabilities = probabilities + [row['count']/full_count]

    # this will hold the sum of probabilities
    cumulative_probabilities = 0

     # this is the number between 0 and 1 that will decide the starting bigram
    random_pick = random.random()
    
    # this loop will increment the probability until it is greater than the random number, this is how we find the selected bigram and thefore the next seed
    for index, probability in enumerate(probabilities):

        cumulative_probabilities = cumulative_probabilities + probability
        
        if random_pick < cumulative_probabilities:

            # setting the amount of spacing accordingly to give that waterfall effect
            print( " "*len(full_sentence) + bigrams_starting_with_seed_word_df.iloc[index]['bigram'])
            next_seed = bigrams_starting_with_seed_word_df.iloc[index]['bigram'].split(" ")[1]

            #recursion since it is a recurrent theme in the module
            return ShannonVisualization(full_sentence + next_seed + " ", next_seed)


final_sentence = ShannonVisualization()
print(final_sentence)

<S> login
      login name
           name on
              on project
                      project that
                           that exists
                                  exists with
                                       with the
                                           the agreements
                                                      agreements between
                                                              between the
                                                                  the entire
                                                                         entire universe
                                                                                  universe of
                                                                                     of a
                                                                                       a reputable
                                                                                                 reputable companies
                                                                                                           companies house
                                                                                                                 house down
                                                                                                                      down on
                                                                                                                         on the
                                                                                                                             the nation
                                                                                                                                    nation or
                                                                                                                                       or eliminate
                                                                                                                                                 eliminate any
                                                                                                                                                     any other
                                                                                                                                                           other visitors
                                                                                                                                                                    visitors who
                                                                                                                                                                        who looks
                                                                                                                                                                              looks like
                                                                                                                                                                                   like a
                                                                                                                                                                                     a lie
                                                                                                                                                                                         lie ahead
                                                                                                                                                                                               ahead of
                                                                                                                                                                                                  of the
                                                                                                                                                                                                      the aerial
                                                                                                                                                                                                             aerial photo
                                                                                                                                                                                                                   photo images
                                                                                                                                                                                                                          images will
                                                                                                                                                                                                                               will decrease
                                                                                                                                                                                                                                        decrease in
                                                                                                                                                                                                                                           in for
                                                                                                                                                                                                                                               for my
                                                                                                                                                                                                                                                  my opinion
                                                                                                                                                                                                                                                          opinion expressed
                                                                                                                                                                                                                                                                    expressed a
                                                                                                                                                                                                                                                                      a a
                                                                                                                                                                                                                                                                        a lifetime
                                                                                                                                                                                                                                                                                 lifetime and
                                                                                                                                                                                                                                                                                     and being
                                                                                                                                                                                                                                                                                           being an
                                                                                                                                                                                                                                                                                              an alley
login name on project that exists with the agreements between the entire universe of a reputable companies house down on the nation or eliminate any other visitors who looks like a lie ahead of the aerial photo images will decrease in for my opinion expressed a a lifetime and being an alley